// <auto-generated />
using System;
using BoilerPlate.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BoilerPlate.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250325193205_Initial_Migration")]
    partial class Initial_Migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("BoilerPlate.Domain.Entities.PKFields.FieldMapping", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT")
                        .HasColumnName("Created")
                        .HasColumnOrder(100);

                    b.Property<string>("DestinationField")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceField")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SourceServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatusEntity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("StatusEntity")
                        .HasColumnOrder(101);

                    b.HasKey("Id");

                    b.HasIndex("SourceServiceId");

                    b.ToTable("FieldMappings");
                });

            modelBuilder.Entity("BoilerPlate.Domain.Entities.PKSourceService.SourceService", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT")
                        .HasColumnName("Created")
                        .HasColumnOrder(100);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceFullUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceServiceDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceServiceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusEntity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("StatusEntity")
                        .HasColumnOrder(101);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SourceServices");
                });

            modelBuilder.Entity("BoilerPlate.Domain.Entities.PKFields.FieldMapping", b =>
                {
                    b.HasOne("BoilerPlate.Domain.Entities.PKSourceService.SourceService", "SourceService")
                        .WithMany()
                        .HasForeignKey("SourceServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceService");
                });
#pragma warning restore 612, 618
        }
    }
}
