global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using System.Net;
global using BoilerPlate.Localization;
global using BoilerPlate.ApiService.Controllers.Base;
global using BoilerPlateProject.Application.Wrappers;